#define COMPONENT hitpoints
#define COMPONENT_BEAUTIFIED KAT - Hitpoints
#include "\x\kat\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS

#ifdef DEBUG_ENABLED_MAIN
    #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_MAIN
    #define DEBUG_SETTINGS DEBUG_SETTINGS_MAIN
#endif

#include "\x\kat\addons\main\script_macros.hpp"

#undef HITPOINT_INDEX_BODY
#undef HITPOINT_INDEX_LARM
#undef HITPOINT_INDEX_RARM
#undef HITPOINT_INDEX_LLEG
#undef HITPOINT_INDEX_RLEG

#undef DEFAULT_TOURNIQUET_VALUES
#undef DEFAULT_FRACTURE_VALUES
#undef DEFAULT_BODYPART_DAMAGE_VALUES

#define PRIORITY_NECK       3
#define PRIORITY_CHEST      4
#define HITPOINT_INDEX_NECK 1
#define HITPOINT_INDEX_CHEST 2
#define HITPOINT_INDEX_BODY 3
#define HITPOINT_INDEX_LARM 4
#define HITPOINT_INDEX_ULARM 5
#define HITPOINT_INDEX_RARM 6
#define HITPOINT_INDEX_URARM 7
#define HITPOINT_INDEX_LLEG 8
#define HITPOINT_INDEX_ULLEG 9
#define HITPOINT_INDEX_RLEG 10
#define HITPOINT_INDEX_URLEG 11

#define DEFAULT_TOURNIQUET_VALUES [0,0,0,0,0,0,0,0,0,0,0,0]
#define DEFAULT_FRACTURE_VALUES [0,0,0,0,0,0,0,0,0,0,0,0]
#define DEFAULT_BODYPART_DAMAGE_VALUES [0,0,0,0,0,0,0,0,0,0,0,0]

#undef IDC_BODY_HEAD
#undef IDC_BODY_NECK
#undef IDC_BODY_TORSO
#undef IDC_BODY_CHEST
#undef IDC_BODY_ARMLEFT
#undef IDC_BODY_ARMUPPERLEFT
#undef IDC_BODY_ARMRIGHT
#undef IDC_BODY_ARMUPPERRIGHT
#undef IDC_BODY_LEGLEFT
#undef IDC_BODY_LEGUPPERLEFT
#undef IDC_BODY_LEGRIGHT
#undef IDC_BODY_LEGUPPERRIGHT
#undef IDC_BODY_ARMLEFT_T
#undef IDC_BODY_ARMUPPERLEFT_T
#undef IDC_BODY_ARMRIGHT_T
#undef IDC_BODY_ARMUPPERRIGHT_T
#undef IDC_BODY_LEGLEFT_T
#undef IDC_BODY_LEGUPPERLEFT_T
#undef IDC_BODY_LEGRIGHT_T
#undef IDC_BODY_LEGUPPERRIGHT_T
#undef IDC_BODY_ARMLEFT_B
#undef IDC_BODY_ARMUPPERLEFT_B
#undef IDC_BODY_ARMRIGHT_B
#undef IDC_BODY_ARMUPPERRIGHT_B
#undef IDC_BODY_LEGLEFT_B
#undef IDC_BODY_LEGUPPERLEFT_B
#undef IDC_BODY_LEGRIGHT_B
#undef IDC_BODY_LEGUPPERRIGHT_B
#undef IDC_BODY_GROUP_S
#undef IDC_BODY_HEAD_S
#undef IDC_BODY_NECK_S
#undef IDC_BODY_TORSO_S
#undef IDC_BODY_CHEST_S
#undef IDC_BODY_ARMLEFT_S
#undef IDC_BODY_ARMUPPERLEFT_S
#undef IDC_BODY_ARMRIGHT_S
#undef IDC_BODY_ARMUPPERRIGHT_S
#undef IDC_BODY_LEGLEFT_S
#undef IDC_BODY_LEGUPPERLEFT_S
#undef IDC_BODY_LEGRIGHT_S
#undef IDC_BODY_LEGUPPERRIGHT_S

#define IDC_BODY_HEAD       6005
#define IDC_BODY_NECK       6006
#define IDC_BODY_TORSO      6010
#define IDC_BODY_CHEST      6011
#define IDC_BODY_ARMLEFT    6015
#define IDC_BODY_ARMUPPERLEFT    6016
#define IDC_BODY_ARMRIGHT   6020
#define IDC_BODY_ARMUPPERRIGHT   6021
#define IDC_BODY_LEGLEFT    6025
#define IDC_BODY_LEGUPPERLEFT    6026
#define IDC_BODY_LEGRIGHT   6030
#define IDC_BODY_LEGUPPERRIGHT    6031
#define IDC_BODY_ARMLEFT_T  6035
#define IDC_BODY_ARMUPPERLEFT_T  6035
#define IDC_BODY_ARMRIGHT_T 6040
#define IDC_BODY_ARMUPPERRIGHT_T 6040
#define IDC_BODY_LEGLEFT_T  6045
#define IDC_BODY_LEGUPPERLEFT_T    6046
#define IDC_BODY_LEGRIGHT_T 6050
#define IDC_BODY_LEGUPPERRIGHT_T    6051
#define IDC_BODY_ARMLEFT_B  6055
#define IDC_BODY_ARMUPPERLEFT_B  6056
#define IDC_BODY_ARMRIGHT_B 6060
#define IDC_BODY_ARMUPPERRIGHT_B 6061
#define IDC_BODY_LEGLEFT_B  6065
#define IDC_BODY_LEGUPPERLEFT_B  6066
#define IDC_BODY_LEGRIGHT_B 6070
#define IDC_BODY_LEGUPPERRIGHT_B 6071
#define IDC_BODY_GROUP_S    6075
#define IDC_BODY_HEAD_S     6080
#define IDC_BODY_NECK_S     6081
#define IDC_BODY_TORSO_S    6085
#define IDC_BODY_CHEST_S    6086
#define IDC_BODY_ARMLEFT_S  6090
#define IDC_BODY_ARMUPPERLEFT_S  6091
#define IDC_BODY_ARMRIGHT_S 6095
#define IDC_BODY_ARMUPPERRIGHT_S 6096
#define IDC_BODY_LEGLEFT_S  6100
#define IDC_BODY_LEGUPPERLEFT_S 6101
#define IDC_BODY_LEGRIGHT_S 6105
#define IDC_BODY_LEGUPPERRIGHT_S 6106

#define POS_X(N) ((N) * GUI_GRID_W + GUI_GRID_CENTER_X)
#define POS_Y(N) ((N) * GUI_GRID_H + GUI_GRID_CENTER_Y)
#define POS_W(N) ((N) * GUI_GRID_W)
#define POS_H(N) ((N) * GUI_GRID_H)

#define PATIENT_INFO_IGUI_BASE_X (safeZoneX + POS_W(2))
#define PATIENT_INFO_IGUI_BASE_Y (safeZoneY + POS_H(1))
#define PATIENT_INFO_IGUI_X (profilenamespace getVariable ['TRIPLES(IGUI,GVAR(patientInfo),X)', 0])
#define PATIENT_INFO_IGUI_Y (profilenamespace getVariable ['TRIPLES(IGUI,GVAR(patientInfo),Y)', 0])
#define PATIENT_INFO_IGUI_OFFSET_X (PATIENT_INFO_IGUI_X - PATIENT_INFO_IGUI_BASE_X)
#define PATIENT_INFO_IGUI_OFFSET_Y (PATIENT_INFO_IGUI_Y - PATIENT_INFO_IGUI_BASE_Y)
