PREP(applyIV);
PREP(checkIV);
PREP(getBloodVolumeChange);
PREP(init);
PREP(removeItemfromMag);
PREP(removeIV);
PREP(retrieveIV);
PREP(treatmentAdvanced_Atropine);
PREP(treatmentAdvanced_AtropineLocal);
PREP(treatmentAdvanced_Carbonate);
PREP(treatmentAdvanced_CarbonateLocal);
<<<<<<< HEAD
PREP(treatmentAdvanced_Fentanyl);
PREP(treatmentAdvanced_Ketamine);
PREP(treatmentAdvanced_medication);
PREP(treatmentAdvanced_medicationLocal);
PREP(treatmentAdvanced_Nalbuphine);
PREP(treatmentAdvanced_Dialysis);
PREP(treatmentAdvanced_DialysisLocal);
=======
PREP(treatmentAdvanced_Generic);
PREP(treatmentAdvanced_GenericLocal);
>>>>>>> parent of 3c83512 (More stuff)
PREP(treatmentAdvanced_Naloxone);
PREP(treatmentAdvanced_NaloxoneLocal);
PREP(treatmentAdvanced_Reorientation);
PREP(treatmentAdvanced_ReorientationLocal);
PREP(treatmentAdvanced_TXA);
PREP(treatmentAdvanced_TXALocal);