PREP(fullHealLocal);
PREP(handleDustInjury);
PREP(handleDustInjuryEffects);
PREP(handleRespawn);
PREP(init);
PREP(initKeybinds);
PREP(treatmentAdvanced_blink);
PREP(treatmentAdvanced_eyewash);
PREP(treatmentAdvanced_eyewasher);
