name: Release Drafter

on:
  push:
    branches:
    - dev-Tomcat

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        if: github.repository == 'Tomcat-SG/KAM'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
