name: Release

on:
  release:
    types: released

permissions:
  contents: write

jobs:
  release-addon:
    runs-on: ubuntu-latest
    steps:
        - name: Set VERSION env
          run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV
        - name: Checkout the source code
          uses: actions/checkout@v2
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1
        - name: Run HEMTT build
          run: hemtt release
        - name: Move release to releases folder
          run:
            version="${{ github.event.release.tag_name }}"
            mv releases/kat-latest.zip "@Kat-Advanced-Medical-${version//[.]/_}.zip"
        - name: Update Release with Files
          uses: softprops/action-gh-release@v1
          with:
            files: ./@Kat-Advanced-Medical-*.zip
            draft: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Fetch Release Changelog
          id: fetch_changelog
          run: |
            release_info=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/MiszczuZPolski/KAM/releases/tags/${{ env.VERSION }}")
            changelog=$(echo "$release_info" | jq -r '.body')
            echo "::set-output name=changelog::$changelog"
        - name: Update to Steam Workshop
          uses: arma-actions/workshop-upload@v1
          with:
            itemId: '2841189207'
            contentPath: './@Kat-Advanced-Medical-*.zip'
            changelog: |
              'https://github.com/MiszczuZPolski/KAM/releases/tag/v${{ env.VERSION }}'
              ${{ steps.fetch_changelog.outputs.changelog }}
          env:
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
