name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release-addon:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the source code
          uses: actions/checkout@v2
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1
        - name: Run HEMTT build
          run: hemtt release
        - name: Update Release with Files
          uses: softprops/action-gh-release@v1
          with:
            files: |
              .hemttout/release//@kam_*.zip
            draft: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Get Release Changelog
          id: get_changelog
          run: |
            release_tag=$(git describe --tags --abbrev=0)
            changelog=$(git log --pretty=format:"- %s" $release_tag..HEAD)
            echo "::set-output name=changelog::${changelog}"
        - uses: arma-actions/workshop-upload@v1
          with:
            itemId: '2841189207'
            contentPath: '.hemttout/release/@kam_*.zip'
            changelog: |
              https://github.com/MiszczuZPolski/KAM/releases/tag/v${{ github.event.ref }}

              Changelog:
              ${{ steps.get_changelog.outputs.changelog }}
          env:
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
