name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release-addon:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the source code
          uses: actions/checkout@v2
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1
        - name: Run HEMTT build
          run: hemtt release
        - name: Update Release with Files
          uses: softprops/action-gh-release@v1
          with:
            files: |
              /home/runner/work/KAM/KAM/releases/kam_*.zip
            draft: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Get Release Changelog
          id: get_changelog
          run: |
            release_tag=$(git describe --tags --abbrev=0)
            changelog=$(git log --pretty=format:"- %s" ${release_tag}..HEAD)
            echo "{name}={value}" >> $GITHUB_OUTPUT
        - uses: arma-actions/workshop-upload@v1
          with:
            itemId: '2841189207'
            contentPath: './home/runner/work/KAM/KAM/releases/kam_*.zip'
            changelog: |

              Changelog:
              ${{ steps.get_changelog.outputs.GITHUB_OUTPUT }}
          env:
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
