name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-addon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT build
        run: hemtt release
      - uses: actions/upload-artifact@v2
        with:
          path: releases/kam_*.zip
          if-no-files-found: error

  release-addon:
    runs-on: ubuntu-latest
    needs: build-addon
    steps:
        - name: Set VERSION env
          run: echo "VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
        - uses: actions/download-artifact@v2
        - name: Update Release with Files
          uses: softprops/action-gh-release@v1
          with:
            files: |
              releases/*
            draft: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - uses: arma-actions/workshop-upload@v1
          with:
            itemId: '2841189207'
            contentPath: 'releases/kam_*.zip'
            changelog: 'https://github.com/MiszczuZPolski/KAM/releases/tag/v${{ env.VERSION }}'
          env:
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
